# This should probably be a statefulSet so we can leverage PVC
{{- if .Values.fullService.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "chart.fullname" . }}-full-service
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.fullService.replicaCount }}
  selector:
    matchLabels:
      app: full-service
      {{- include "chart.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "chart.fullname" . }}-full-service
  template:
    metadata:
      annotations:
        {{- toYaml .Values.fullService.podAnnotations | nindent 8 }}
      labels:
        app: full-service
        {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      terminationGracePeriodSeconds: 30
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 2000
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
      - name: full-service
        securityContext:
          capabilities:
            drop:
            - all
          readOnlyRootFilesystem: true
        image: "{{ .Values.fullService.image.repository }}:{{ .Values.fullService.image.tag }}"
        imagePullPolicy: Always
        args:
          {{- toYaml .Values.fullService.args | nindent 10 }}
        ports:
        - name: full-service
          containerPort: 9090
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /data
        resources:
          {{- toYaml .Values.fullService.resources | nindent 12 }}
      nodeSelector:
        {{- toYaml .Values.fullService.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.fullService.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.fullService.tolerations | nindent 8 }}
      {{- if eq .Values.fullService.persistence.enabled false }}
      volumes:
      - name: data
        emptyDir: {}
      {{- end }}
  {{- if .Values.fullService.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      {{- toYaml .Values.fullService.persistence.spec | nindent 6 }}
  {{- end }}
{{- end }}
