{{ if eq .Values.fullService.configMap.external false }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullServiceMapName" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  {{ toYaml .Values.fullService.configMap.data | nindent 4}}
{{- end }}