{{ if eq .Values.mobotConfig.secret.external false }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "chart.mobotSecretName" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  SECRET_KEY: {{ .Values.mobotConfig.secretKey | b64enc }}
{{- end }}
