{{- if eq .Values.mobotDatabase.secret.external false }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.mobotDatabaseSecretName" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
data:
  postgresql-password: "{{ .Values.mobotDatabase.password | b64enc }}"
{{- end }}
