apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-signald
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 15432
      targetPort: signald
      protocol: TCP
      name: signald
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
    app: signald
