# Generated by Django 3.2.7 on 2021-09-28 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobot_client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount_pmob',
        ),
        migrations.AddField(
            model_name='payment',
            name='amount_mob',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Amount of payment, if known', max_digits=12, null=True),
        ),
    ]
