# Generated by Django 3.2.7 on 2021-09-28 18:40

from decimal import Decimal
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mobot_client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drop',
            name='initial_mob',
        ),
        migrations.AddField(
            model_name='drop',
            name='initial_coin_amount_mob',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=12, verbose_name='Initial mob award amount'),
        ),
        migrations.AlterField(
            model_name='drop',
            name='advertisment_start_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='drop',
            name='end_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='drop',
            name='pre_drop_description',
            field=models.TextField(default='MOB'),
        ),
        migrations.AlterField(
            model_name='drop',
            name='start_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='drop',
            name='timezone',
            field=models.CharField(default='Europe/London', max_length=255),
        ),
    ]
