# Generated by Django 3.0.4 on 2021-08-29 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobot_client', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sku',
            options={'base_manager_name': 'available', 'ordering': ['sort_order']},
        ),
    ]
