# Generated by Django 3.2.7 on 2021-09-24 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobot_client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawsignalmessage',
            name='timestamp',
            field=models.FloatField(help_text='Raw unix timestamp from the message data'),
        ),
    ]
