# Generated by Django 3.2.7 on 2021-09-05 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobot_client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='processed',
            field=models.DateTimeField(blank=True, db_index=True, help_text='The time at which a payment was processed', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='processing',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_pmob', models.PositiveIntegerField()),
                ('receipt', models.TextField(blank=True, default=None, help_text='Full-service receipt', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.DateTimeField(blank=True, help_text='The date a payment was processed, if it was.', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Time of last update')),
                ('status', models.SmallIntegerField(choices=[('Failure', 'Failure'), ('TransactionPending', 'Pending'), ('TransactionSuccess', 'Success')], default='TransactionPending', help_text='Status of payment')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='mobot_client.customer')),
            ],
        ),
        migrations.CreateModel(
            name='MobotResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.DateTimeField(blank=True, null=True)),
                ('incoming_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='mobot_client.message')),
                ('incoming_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='mobot_client.payment')),
                ('response_message', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response', to='mobot_client.message')),
                ('response_payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response', to='mobot_client.payment')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='payment',
            field=models.OneToOneField(blank=True, help_text='Attached payment, if it exists', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message', to='mobot_client.payment'),
        ),
    ]
