# Generated by Django 3.0.4 on 2021-08-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobot_client', '0002_auto_20210829_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drop',
            name='number_restriction',
            field=models.CharField(default='+44', max_length=4),
        ),
    ]
