# Generated by Django 3.2.7 on 2021-09-28 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobot_client', '0002_auto_20210928_0007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['customer_id', 'date', '-processing', 'updated']},
        ),
    ]
