# Generated by Django 3.2.7 on 2021-09-06 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobot_client', '0002_auto_20210905_2159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['date', '-processing', 'processed']},
        ),
    ]
