# Generated by Django 3.2.7 on 2021-09-21 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobot_client', '0002_auto_20210921_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.DeleteModel(
            name='PaymentVerification',
        ),
    ]
