# Generated by Django 3.2.7 on 2021-09-07 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobot_client', '0003_alter_message_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobotresponse',
            name='processed',
        ),
    ]
