# Generated by Django 3.2.7 on 2021-09-02 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobot_client', '0003_auto_20210902_2106'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dropsession',
            unique_together={('customer', 'drop')},
        ),
    ]
