# Generated by Django 3.2.7 on 2021-10-04 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobot_client', '0003_alter_message_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'get_latest_by': ['date'], 'ordering': ['customer_id', 'date', '-processing', 'updated']},
        ),
    ]
