# Generated by Django 3.2.7 on 2021-09-02 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobot_client', '0004_alter_dropsession_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dropsession',
            options={'ordering': ('-state', '-created_at')},
        ),
    ]
