# Generated by Django 3.2.7 on 2021-09-07 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobot_client', '0004_remove_mobotresponse_processed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['date', '-payment', '-processing', 'processed']},
        ),
    ]
