# Generated by Django 3.0.4 on 2021-08-29 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobot_client', '0005_auto_20210829_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drop',
            name='initial_coin_limit',
        ),
    ]
