# Generated by Django 3.2.7 on 2021-09-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobot_client', '0005_alter_message_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='processed',
            field=models.DateTimeField(blank=True, db_index=True, help_text='The time at which a message was finished processing', null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='processing',
            field=models.DateTimeField(blank=True, help_text='The time we started processing a message', null=True),
        ),
    ]
