# Generated by Django 3.2.7 on 2021-09-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobot_client', '0005_alter_dropsession_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dropsession',
            options={'ordering': ('-state', '-updated')},
        ),
        migrations.AddField(
            model_name='dropsession',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dropsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
