# Generated by Django 3.2.7 on 2021-09-07 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobot_client', '0006_auto_20210907_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.SmallIntegerField(choices=[(-1, 'Error'), (0, 'Not Processed'), (1, 'Processed')], default=0),
        ),
        migrations.CreateModel(
            name='ProcessingError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobot_client.message')),
            ],
        ),
    ]
