# Generated by Django 3.0.4 on 2021-08-30 00:02

from django.db import migrations, models
import mobot_client.models.phone_numbers


class Migration(migrations.Migration):

    dependencies = [
        ('mobot_client', '0006_remove_drop_initial_coin_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=mobot_client.models.phone_numbers.PhoneNumberField(db_index=True, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='drop',
            name='country_code_restriction',
            field=models.CharField(default='GB', max_length=3),
        ),
        migrations.AlterField(
            model_name='drop',
            name='country_long_name_restriction',
            field=models.CharField(default='United Kingdom', max_length=255),
        ),
        migrations.AlterField(
            model_name='drop',
            name='currency_symbol',
            field=models.CharField(default='$', max_length=1),
        ),
        migrations.AlterField(
            model_name='drop',
            name='timezone',
            field=models.CharField(default='UTC', max_length=6),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sku',
            name='identifier',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
