# Generated by Django 3.2.7 on 2021-09-08 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobot_client', '0006_auto_20210903_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drop',
            name='number_restriction',
            field=models.CharField(blank=True, default='+44', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='dropsession',
            unique_together=set(),
        ),
    ]
