# Generated by Django 3.2.7 on 2021-09-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobot_client', '0007_auto_20210907_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.SmallIntegerField(choices=[(-1, 'Error'), (0, 'Not Processed'), (1, 'Processing'), (2, 'Processed')], default=0),
        ),
    ]
