# Generated by Django 3.0.4 on 2021-08-30 17:34

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('mobot_client', '0007_auto_20210830_0002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AlterModelManagers(
            name='dropsession',
            managers=[
                ('active_sessions', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='chatbotsettings',
            name='avatar_filename',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='chatbotsettings',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dropsession',
            name='bonus_coin_claimed',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drop_sessions', to='mobot_client.BonusCoin'),
        ),
    ]
