# Generated by Django 3.2.7 on 2021-09-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobot_client', '0008_alter_message_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='direction',
            field=models.PositiveIntegerField(choices=[(0, 'received'), (1, 'sent')], db_index=True),
        ),
    ]
