# Generated by Django 3.0.4 on 2021-08-30 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobot_client', '0008_auto_20210830_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drop',
            name='timezone',
            field=models.CharField(default='UTC', max_length=255),
        ),
    ]
