# Generated by Django 3.0.4 on 2021-08-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobot_client', '0009_sku_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='drop',
            name='country_code_restriction',
            field=models.TextField(default='GB'),
        ),
        migrations.AddField(
            model_name='order',
            name='conversion_rate_mob_to_currency',
            field=models.FloatField(default=0.0),
        ),
    ]
