# Generated by Django 3.0.4 on 2021-08-30 22:50

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('mobot_client', '0009_auto_20210830_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128),
        ),
    ]
