# Generated by Django 3.0.4 on 2021-08-31 16:39

import datetime
from django.db import migrations, models
import django.db.models.manager
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mobot_client', '0010_auto_20210830_2250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonuscoin',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='drop',
            options={},
        ),
        migrations.AlterModelOptions(
            name='dropsession',
            options={'base_manager_name': 'active_sessions'},
        ),
        migrations.AlterModelManagers(
            name='bonuscoin',
            managers=[
                ('available', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='dropsession',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 31, 16, 39, 34, 687448, tzinfo=utc)),
        ),
    ]
