# Generated by Django 3.0.4 on 2021-08-05 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobot_client', '0010_auto_20210805_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='drop',
            name='max_refund_transaction_fees_covered',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CustomerDropRefunds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_times_refunded', models.PositiveIntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobot_client.Customer')),
                ('drop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobot_client.Drop')),
            ],
        ),
    ]
