# Generated by Django 3.0.4 on 2021-08-31 16:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mobot_client', '0011_auto_20210831_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropsession',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
