# Generated by Django 3.0.4 on 2021-08-05 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobot_client', '0011_auto_20210805_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='drop',
            name='country_long_name_restriction',
            field=models.TextField(default='United Kingdom'),
        ),
    ]
