# Generated by Django 3.0.4 on 2021-08-31 17:12

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('mobot_client', '0012_auto_20210831_1641'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bonuscoin',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='dropsession',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('active_sessions', django.db.models.manager.Manager()),
            ],
        ),
    ]
