# Copyright (c) 2021 MobileCoin. All rights reserved.

# Generated by Django 3.0.4 on 2021-06-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobot_client', '0005_chatbotsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='drop',
            name='conversion_rate',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='drop',
            name='currency_symbol',
            field=models.TextField(default='$'),
        ),
    ]
