# Generated by Django 3.0.4 on 2021-05-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobot_client', '0005_drop_pre_drop_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='privacy_policy_url',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
    ]
