# Generated by Django 3.0.4 on 2021-05-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobot_client', '0008_drop_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
