# Generated by Django 3.0.4 on 2021-05-19 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobot_client', '0002_dropsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='received_sticker_pack',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('direction', models.PositiveIntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobot_client.Customer')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobot_client.Store')),
            ],
        ),
    ]
