# Generated by Django 3.0.4 on 2021-05-19 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobot_client', '0003_auto_20210519_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
    ]
