# Generated by Django 3.0.4 on 2021-05-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobot_client', '0004_remove_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='drop',
            name='pre_drop_description',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
    ]
