# Generated by Django 3.0.4 on 2021-05-19 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobot_client', '0006_store_privacy_policy_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='drop',
            name='number_restriction',
            field=models.TextField(default='+44'),
            preserve_default=False,
        ),
    ]
