# Generated by Django 3.0.4 on 2021-05-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobot_client', '0007_drop_number_restriction'),
    ]

    operations = [
        migrations.AddField(
            model_name='drop',
            name='timezone',
            field=models.TextField(default='Europe/London'),
            preserve_default=False,
        ),
    ]
