# Generated by Django 3.0.4 on 2021-05-21 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobot_client', '0009_customer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='date',
            new_name='occured_at',
        ),
    ]
