# Generated by Django 3.0.4 on 2021-05-21 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobot_client', '0011_auto_20210521_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
    ]
