name: tag

# Create a tag on push to main.
# Will automatically bump "#patch" by default
# Use "#major", "#minor", "#patch". "#none" in commit message to adjust bump.

on:
  push:
    branches:
    - main

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Github Tag Bump
      uses: anothrNick/github-tag-action@1.35.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: "true"
        DEFAULT_BUMP: patch
